import { C } from './colors.js';

// ── ARCADE GAMES (16) ──
export const PLAY_GAMES = [
  { id:"finalkick",  name:"Final Kick",      emoji:"⚽",   players:"2",   time:"1-2m",  type:"Skill",     color:C.cyan,   desc:"Penalty kick 1v1. Aim your shot, pick your save direction.", hot:true,  difficulty:5, mp:{mode:"100 Keepers",    count:"1v100",      badge:"🥅"} },
  { id:"finalkick2", name:"Final Kick 2",    emoji:"⚽🔥", players:"2",   time:"2-3m",  type:"Precision",  color:C.gold,   desc:"Double puff! Aim X-axis + Y-axis separately.",              hot:true,  difficulty:6, mp:{mode:"Pressure Cooker",count:"8 players",  badge:"🔥"} },
  { id:"hotpotato",  name:"Hot Potato",      emoji:"💣",   players:"3-8", time:"1-3m",  type:"Luck",      color:C.orange, desc:"Bomb jumps randomly. Puff to pass. Get caught = eliminated.", difficulty:2, mp:{mode:"Pass the Nuke",  count:"16 players", badge:"☢️"} },
  { id:"russian",    name:"Russian Roulette",emoji:"🎲",   players:"2-6", time:"1-2m",  type:"Luck",      color:C.red,    desc:"Take turns puffing. Random elimination each round. Maximum tension.", difficulty:2, mp:{mode:"The Gauntlet",  count:"1,000→1",    badge:"💀"} },
  { id:"wildwest",   name:"Wild West Duel",  emoji:"🤠",   players:"2",   time:"1-2m",  type:"Reaction",  color:C.gold,   desc:"Best of 5 showdown! Wait for DRAW, puff fastest. Reaction time in ms.", hot:true, difficulty:5, mp:{mode:"High Noon Town",count:"8 bracket",  badge:"🌵"} },
  { id:"balloon",    name:"Balloon Pop",     emoji:"🎈",   players:"2-8", time:"1-3m",  type:"Strategy",  color:C.pink,   desc:"Puff inflates the balloon. Pop it and you lose.",           difficulty:4, mp:{mode:"Relay Race",     count:"2 teams×4",  badge:"🏁"} },
  { id:"puffpong",   name:"Puff Pong",       emoji:"🏓",   players:"2",   time:"1-2m",  type:"Skill",     color:C.green,  desc:"Virtual ping pong. Puff = hit the ball. Timing is everything.", difficulty:5, mp:{mode:"Doubles Chaos",count:"2v2",          badge:"🎾"} },
  { id:"rhythm",     name:"Rhythm Puff",     emoji:"🎵",   players:"1-4", time:"1-3m",  type:"Rhythm",    color:C.purple, desc:"Notes fall down, puff on beat. Guitar Hero style.",          difficulty:5, mp:{mode:"Band Battle",    count:"4-piece band",badge:"🎸"} },
  { id:"tugofwar",   name:"Tug of War",      emoji:"💪",   players:"2-8", time:"30s-1m",type:"Team",      color:C.blue,   desc:"Two teams puff nonstop. Stronger side wins.",               hot:true,  difficulty:4, mp:{mode:"50v50 War",      count:"50v50",      badge:"⚔️"} },
  { id:"hooked",     name:"Hooked",          emoji:"🎣",   players:"1",   time:"2-5m",  type:"Skill",     color:C.blue,   desc:"Stack fishing! Puff to reel in fish. Control your suction!", difficulty:4, mp:{mode:"Fishing Tournament",count:"8 anglers",badge:"🐟"} },
  { id:"rps",        name:"Puff RPS",        emoji:"✊",   players:"2",   time:"1-2m",  type:"Strategy",  color:C.purple, desc:"Rock Paper Scissors with Puff Power!",                      hot:true,  difficulty:2, mp:{mode:"Thunderdome",    count:"16 bracket", badge:"⚡"} },
  { id:"beatdrop",   name:"Beat Drop",       emoji:"🎧",   players:"4",   time:"3-5m",  type:"Music",     color:C.pink,   desc:"4 DJs compete — release your puff at the EXACT beat drop! Closest timing wins.", difficulty:4, mp:{mode:"DJ Battle",count:"4 DJs",badge:"🎤"} },
  { id:"puffclock",  name:"Puff Clock",      emoji:"⏱️",  players:"1-100+",time:"3-5m", type:"Precision", color:C.orange, desc:"Puff for EXACTLY the target time. Closest wins!",           difficulty:5, mp:{mode:"World Sync",     count:"500+ players",badge:"🌍"} },
  { id:"pufflimbo",  name:"Puff Limbo",      emoji:"🎪",   players:"1-50",time:"3-5m",  type:"Endurance", color:C.orange, desc:"Target puff gets longer each round. Survive the blinker!",  difficulty:5, mp:{mode:"The Eliminator", count:"50→1",        badge:"💀"} },
  { id:"puffderby",  name:"Puff Derby",      emoji:"🏇",   players:"6",   time:"2-3m",  type:"Racing",    color:C.green,  desc:"Pick a horse. Spam puff to make it run!",                   difficulty:2, mp:{mode:"Grand National", count:"6 horses×2",  badge:"🐴"} },
  { id:"tankwar",    name:"Tank War",         emoji:"🔫",  players:"1-4", time:"2-3m",  type:"Artillery", color:"#4CAF50",desc:"Aim, fire, destroy! Tap to shoot, puff for super shots!",  difficulty:3, hot:true, mp:{mode:"Clan Wars",count:"4v4",badge:"💥"} },
  { id:"fishwar",    name:"Fish War",         emoji:"🐟",  players:"1-4", time:"2-3m",  type:"Survival",  color:"#3B82F6",desc:"Eat smaller fish, evolve, survive! Puff to boost!",         difficulty:3, hot:true, mp:{mode:"Ocean Royale",count:"50 fish BR",badge:"🌊"} },
  { id:"rooftoppuff",name:"Rooftop Puff",     emoji:"🏃",  players:"1-4", time:"1-3m",  type:"Runner",    color:"#00E5FF",desc:"Parkour across rooftops! Tap to jump, puff to boost!",      difficulty:2, hot:true, mp:{mode:"Race",count:"4 runners",badge:"🏙️"} },
];

// ── STAGE SHOWS (6) ──
export const SHOW_GAMES = [
  { id:"vibecheck",      name:"Vibe Check",       emoji:"🧠", players:"1-100+", time:"5-15m", type:"Trivia",    color:C.gold,   desc:"Trivia Game Show. Host asks, contestants answer, audience votes.", live:true, difficulty:3, mp:{mode:"Crowd vs Contestant",count:"1+99",badge:"🧠"} },
  { id:"higherlower",    name:"Higher or Lower",  emoji:"📊", players:"1-100+", time:"5-10m", type:"Knowledge", color:C.cyan,   desc:"Guess if the next number is higher or lower. Streak = big rewards.", live:true, difficulty:3, mp:{mode:"Chain Gang",count:"10 relay",badge:"🔗"} },
  { id:"pricepuff",      name:"The Price is Puff",emoji:"💰", players:"2-50+",  time:"5-10m", type:"Knowledge", color:C.green,  desc:"Guess the product price. Closest wins.", live:true, difficulty:4, mp:{mode:"Bidding Frenzy",count:"6 players",badge:"💸"} },
  { id:"survivaltrivia", name:"Survival Trivia",  emoji:"🏆", players:"2-100+", time:"5-15m", type:"Trivia",    color:C.purple, desc:"Answer correctly or get eliminated. Last one standing wins!", live:true, difficulty:3, mp:{mode:"Last Brain Standing",count:"100→1",badge:"🧠"} },
  { id:"simonpuffs",     name:"Simon Puffs",       emoji:"🔴", players:"1-50+",  time:"3-8m",  type:"Memory",    color:C.red,    desc:"Remember the pattern, repeat with puffs. Memory master!", live:true, difficulty:3, mp:{mode:"Mind Meld",count:"4 co-op",badge:"🧩"} },
  { id:"puffauction",    name:"Puff Auction",      emoji:"🔨", players:"2-50+",  time:"3-8m",  type:"Strategy",  color:C.lime,   desc:"Bid with your lungs! Biggest puff wins the auction.", live:true, difficulty:4, mp:{mode:"Auction House Madness",count:"16 bidders",badge:"🏛️"} },
];

// ── ORACLE/FORTUNE GAMES (12) ──
export const ORACLE_GAMES = [
  { id:"crystalball",   name:"Crystal Ball",   emoji:"🔮", players:"1", time:"1-2m", type:"Prediction", color:"#9333EA", desc:"Yes/No universal predictions. Puff to decide destiny.", difficulty:1 },
  { id:"strainbattle",  name:"Strain Battle",  emoji:"🌿", players:"1", time:"2-3m", type:"Vote",       color:"#22C55E", desc:"Vote for the best strain in epic matchups.", difficulty:1 },
  { id:"matchpredictor",name:"Match Predictor",emoji:"📊", players:"1", time:"1-2m", type:"Sports",     color:"#3B82F6", desc:"Predict WC match outcomes. Win/Draw/Lose.", difficulty:1 },
  { id:"dailypicks",    name:"Daily Picks",    emoji:"📅", players:"1", time:"2-3m", type:"Daily",      color:"#F97316", desc:"3 daily predictions with streak multipliers.", difficulty:1 },
  { id:"puffslots",     name:"Puff Slots",     emoji:"🎰", players:"1", time:"2-3m", type:"Fortune",    color:"#FFD700", desc:"3-reel slot machine. Puff to spin the reels!", difficulty:1 },
  { id:"puffblackjack", name:"Puff Blackjack", emoji:"🃏", players:"1", time:"3-5m", type:"Fortune",    color:"#22C55E", desc:"Classic blackjack with puff controls. Hit or Stand!", difficulty:1 },
  { id:"coinflip",      name:"Coin Flip",      emoji:"🪙", players:"1", time:"1-2m", type:"Fortune",    color:"#F59E0B", desc:"50/50 flip with puff confidence multiplier.", difficulty:1 },
  { id:"crapsnclouds",  name:"Craps & Clouds", emoji:"🎲", players:"1", time:"2-3m", type:"Fortune",    color:"#EF4444", desc:"Dice game where your puff controls the roll!", difficulty:1 },
  { id:"mysterybox",    name:"Mystery Box",    emoji:"🎁", players:"1", time:"2-3m", type:"Fortune",    color:"#FFD700", desc:"3 mystery boxes. Pick one. Puff to reveal!", difficulty:1 },
  { id:"scratchpuff",   name:"Scratch & Puff", emoji:"🎫", players:"1", time:"2-3m", type:"Fortune",    color:"#EC4899", desc:"6 scratch areas. Puff to scratch. Match 3 wins!", difficulty:1 },
  { id:"fortunecookie", name:"Fortune Cookie", emoji:"🥠", players:"1", time:"1-2m", type:"Fortune",    color:"#F97316", desc:"Crack open wisdom + coins. Blinker = golden cookie!", difficulty:1 },
  { id:"treasuremap",   name:"Treasure Map",   emoji:"🗺️",players:"1", time:"3-5m", type:"Fortune",    color:"#FFD700", desc:"16 tiles. Find 3 treasures. Avoid 3 bombs!", difficulty:1 },
];

// ── GAME CONFIG — drives Start Screen for all 37 games ──
export const GAME_CONFIG = {
  // Arcade
  tankwar:    { modes:[{id:"1v1",emoji:"🎯",name:"1v1 Duel",sub:"Classic"},{id:"2v2",emoji:"👥",name:"2v2 Teams",sub:"You + ally"},{id:"ffa",emoji:"💀",name:"Free-for-All",sub:"4 tanks"},{id:"boss",emoji:"🐉",name:"Boss Battle",sub:"Co-op"}], puffGame:false, stats:[{v:"680",l:"online"},{v:"58%",l:"win rate"},{v:"312",l:"max dmg"}], hotStats:["A blinker shot destroyed 3 tanks at once 💀","Someone won 1v4 FFA with 1 HP 🤯"], htp:[{e:"🎯",t:"Aim cannon",d:"Pointer sweeps left-right. Tap to lock."},{e:"💪",t:"Set power",d:"Bar fills 0-100%. 50-80% = best zone."},{e:"💨",t:"Puff for bonus",d:"+15% damage. Blinker = +20% LEGENDARY!"},{e:"🏆",t:"Destroy enemies",d:"Wind affects shots. Terrain destructible."}], reward:60 },
  fishwar:    { modes:[{id:"solo",emoji:"🐟",name:"Solo",sub:"500pts target"},{id:"1v1",emoji:"🎯",name:"1v1",sub:"Eliminate bot"},{id:"pvp",emoji:"💀",name:"PvP",sub:"Last standing"},{id:"boss",emoji:"🐉",name:"Boss",sub:"Defeat boss"}], puffGame:false, stats:[{v:"520",l:"swimming"},{v:"8",l:"forms"},{v:"45",l:"max pts"}], hotStats:["Someone evolved to Dragon in 90 seconds 🐉","A fish ate 47 others in one game 🤯"], htp:[{e:"🏊",t:"Auto-swim",d:"Fish moves forward automatically."},{e:"👆",t:"Tap to turn",d:"Tap anywhere to change direction."},{e:"💨",t:"Puff = boost",d:"Hold puff for x2.2 speed. Fuel limited."},{e:"🍽️",t:"Eat & evolve",d:"Eat smaller fish. Every 5 = level up!"}], reward:60 },
  rooftoppuff:{ modes:[{id:"solo",emoji:"🏃",name:"Solo Run",sub:"Run forever"},{id:"1v1",emoji:"🎯",name:"1v1 Race",sub:"Beat the bot"},{id:"race",emoji:"🏁",name:"Race 4",sub:"4 runners"}], puffGame:false, stats:[{v:"430",l:"running"},{v:"342m",l:"record"},{v:"4",l:"runners"}], hotStats:["Someone ran 500m without double jump 💀","Blinker boost across a 60px gap 🔥🏃"], htp:[{e:"👆",t:"Tap to jump",d:"Tap screen to jump. Tap again mid-air for double jump."},{e:"💨",t:"Hold = boost",d:"Hold puff bar for speed x1.5 + jump x1.2."},{e:"🪙",t:"Collect coins",d:"Grab coins on rooftops for bonus score."},{e:"🏆",t:"Survive longest",d:"Gaps widen, platforms shrink. Don't fall!"}], reward:60 },
  finalkick:  { modes:null, puffGame:false, stats:[{v:"2.1K",l:"playing"},{v:"62%",l:"win rate"},{v:"15",l:"top goals"}], hotStats:["NeonQueen scored from the moon 🌙","A blinker kick bent like Beckham 🔥"], htp:[{e:"👆",t:"Pick zone",d:"Choose where to aim your shot."},{e:"💨",t:"Kick power",d:"Hold to charge. Release in sweet spot."},{e:"🧤",t:"Save phase",d:"Dive to block the AI's shot."},{e:"🏆",t:"Win 5 rounds",d:"First to 3 goals wins the match!"}], reward:80 },
  finalkick2: { modes:null, puffGame:false, stats:[{v:"356",l:"playing"},{v:"54%",l:"win rate"},{v:"0.02s",l:"precision"}], hotStats:["Someone hit perfect X AND Y on a blinker 💀"], htp:[{e:"↔️",t:"Puff 1: X-aim",d:"First puff controls horizontal aim."},{e:"↕️",t:"Puff 2: Y-aim",d:"Second puff controls vertical aim."},{e:"💨",t:"Double precision",d:"Two puffs, one shot. Maximum skill."},{e:"🏆",t:"Outscore AI",d:"5 rounds of precision penalties."}], reward:80 },
  wildwest:   { modes:null, puffGame:false, stats:[{v:"720",l:"dueling"},{v:"0.18s",l:"fastest"},{v:"5",l:"rounds"}], hotStats:["Someone drew in 0.18s... is that legal? 🤠","Blinker draw — who blinkers in a DUEL?! 💀"], htp:[{e:"👀",t:"Staredown",d:"Wait for the DRAW signal..."},{e:"💨",t:"DRAW!",d:"Puff fastest when you see DRAW!"},{e:"⏱️",t:"Reaction time",d:"Measured in milliseconds."},{e:"🏆",t:"Best of 5",d:"Win 3 rounds to claim victory."}], reward:60 },
  hotpotato:  { modes:null, puffGame:false, stats:[{v:"890",l:"playing"},{v:"16",l:"players"},{v:"3s",l:"avg hold"}], hotStats:["Someone held the bomb for 8 seconds on PURPOSE 💀","YEET pass across 5 players in 0.2s"], htp:[{e:"💣",t:"Bomb incoming!",d:"The bomb jumps to you randomly."},{e:"💨",t:"Puff to pass",d:"Puff fast to pass it along!"},{e:"💥",t:"Don't get caught",d:"Holding when timer hits = eliminated."},{e:"🏆",t:"Last alive",d:"Survive to win!"}], reward:50 },
  russian:    { modes:[{id:"quick",emoji:"🎲",name:"Quick (6)",sub:"6 players"},{id:"gauntlet",emoji:"💀",name:"Gauntlet",sub:"1,000→1"}], puffGame:false, stats:[{v:"167",l:"surviving"},{v:"17%",l:"survival"},{v:"12",l:"longest"}], hotStats:["Someone dodged 8 chambers in a row 🤯","The chamber was angry today 😤"], htp:[{e:"🔫",t:"Spin chamber",d:"The revolver spins..."},{e:"💨",t:"Pull trigger",d:"Puff to pull. Pray it clicks."},{e:"🫁",t:"Blinker dodge",d:"5s blinker = 80% dodge chance!"},{e:"🏆",t:"Survive",d:"Last one standing wins."}], reward:50 },
  balloon:    { modes:null, puffGame:true,  stats:[{v:"145",l:"inflating"},{v:"73%",l:"pop rate"},{v:"8",l:"players"}], hotStats:["Someone popped on their FIRST puff 😂","Balloon survived 47 puffs — record!"], htp:[{e:"🎈",t:"Inflate balloon",d:"Each puff inflates it more."},{e:"😰",t:"Don't pop it!",d:"Pop it = you're eliminated."},{e:"💨",t:"Real puff = real fear",d:"Feel it inflate with your lungs!"},{e:"🏆",t:"Last alive",d:"Be the last one NOT popping."}], reward:50 },
  puffpong:   { modes:null, puffGame:false, stats:[{v:"289",l:"rallying"},{v:"5",l:"to win"},{v:"23",l:"longest rally"}], hotStats:["23-hit rally — both players forgot to breathe 🏓","NUCLEAR PUFF smash — ball broke the sound barrier 💥"], htp:[{e:"🏓",t:"Hit the ball",d:"Puff or tap to return the ball."},{e:"↕️",t:"Move paddle",d:"Tap up/down to position."},{e:"💨",t:"Power shot",d:"Puff for stronger returns."},{e:"🏆",t:"First to 5",d:"Score 5 points to win."}], reward:60 },
  rhythm:     { modes:null, puffGame:false, stats:[{v:"134",l:"jamming"},{v:"50",l:"max combo"},{v:"15",l:"max miss"}], hotStats:["x50 combo — inhuman rhythm! 🎵💨","Someone missed every note. Every. Single. One. 😂"], htp:[{e:"🎵",t:"Notes fall down",d:"Tap the matching lane on beat."},{e:"🔥",t:"Build combos",d:"Hit consecutive notes for multiplier."},{e:"💨",t:"Puff for power",d:"Puff on beat for bonus points!"},{e:"🏆",t:"Survive 15 misses",d:"Miss 15 notes = game over."}], reward:60 },
  tugofwar:   { modes:null, puffGame:true,  stats:[{v:"312",l:"pulling"},{v:"50v50",l:"war size"},{v:"47",l:"avg puffs"}], hotStats:["Team fell into mud in 4 seconds flat 😂💀","Someone did 89 puffs in one game — LUNGS 🫁"], htp:[{e:"💪",t:"PULL!",d:"Puff continuously to pull the rope."},{e:"🫁",t:"Puff = power",d:"Harder puff = stronger pull."},{e:"🤝",t:"Team effort",d:"Your whole team pulls together."},{e:"🏆",t:"Pull them in!",d:"Drag the other team into the mud!"}], reward:60 },
  hooked:     { modes:null, puffGame:false, stats:[{v:"410",l:"fishing"},{v:"🐟",l:"rare catch"},{v:"8",l:"max stack"}], hotStats:["Caught Sir Gill-a-lot on a blinker reel 🎣👑","Line snapped at 98% tension — heartbreaking 💔"], htp:[{e:"🎣",t:"Cast line",d:"Puff to cast into the water."},{e:"🐟",t:"Fish bites!",d:"A fish appears on your hook."},{e:"💨",t:"Reel in",d:"Hold puff to control suction."},{e:"⚠️",t:"Watch tension",d:"Too much = line snaps!"}], reward:60 },
  rps:        { modes:null, puffGame:false, stats:[{v:"540",l:"throwing"},{v:"43%",l:"pick rock"},{v:"5",l:"best of"}], hotStats:["Everyone picks rock first. Be different. 🪨","Blinker power throw — the ground SHOOK 💀"], htp:[{e:"✊",t:"Pick your throw",d:"Rock, Paper, or Scissors."},{e:"💨",t:"Charge power",d:"Hold puff for power multiplier."},{e:"⚔️",t:"Clash!",d:"See who wins the round."},{e:"🏆",t:"Best of 5",d:"Win 3 rounds to claim victory."}], reward:60 },
  beatdrop:   { modes:null, puffGame:false, stats:[{v:"245",l:"dropping"},{v:"12ms",l:"best timing"},{v:"4",l:"DJs compete"}], hotStats:["BLINKER PERFECT — 8ms off the beat 🎧💀","DJ Haze released 3ms early... LEGENDARY timing ✨"], htp:[{e:"🎧",t:"Beat builds up",d:"Music tension rises for 3-8 seconds."},{e:"💨",t:"Hold your puff",d:"Tap, dry puff, real puff, or blinker hold."},{e:"🎵",t:"RELEASE on DROP!",d:"Release at the EXACT moment the beat drops."},{e:"🏆",t:"4 rounds, best avg",d:"4 players compete. Closest timing wins!"}], reward:80 },
  puffclock:  { modes:null, puffGame:true,  stats:[{v:"310",l:"timing"},{v:"±0.02s",l:"record"},{v:"6s",l:"max target"}], hotStats:["Someone puffed for 3.470s on a 3.47 target — INHUMAN ⏱️💀"], htp:[{e:"⏱️",t:"See the target",d:"Target time shown (e.g., 3.47s)."},{e:"💨",t:"Puff that long",d:"Hold your puff for EXACTLY that time."},{e:"🎯",t:"Precision counts",d:"Closest to target wins."},{e:"🏆",t:"Body control",d:"Your lungs ARE the clock."}], reward:50 },
  pufflimbo:  { modes:null, puffGame:true,  stats:[{v:"178",l:"surviving"},{v:"5.0s",l:"blinker round"},{v:"50",l:"enter"}], hotStats:["Someone survived the 5.0s blinker round — LEGEND 💀👑"], htp:[{e:"🎪",t:"Target puff",d:"Each round has a longer target."},{e:"💨",t:"Hold to survive",d:"Puff for the EXACT duration."},{e:"💀",t:"Fall short = out",d:"Stop too early = eliminated."},{e:"🏆",t:"Survive the blinker",d:"Final round: 5.0s BLINKER!"}], reward:50 },
  puffderby:  { modes:null, puffGame:true,  stats:[{v:"420",l:"racing"},{v:"6",l:"horses"},{v:"30s",l:"race time"}], hotStats:["Sir Puffs-a-Lot won by a NOSE 🏇","Someone ran out of stamina at 95% — tragic 😢"], htp:[{e:"🏇",t:"Pick your horse",d:"6 horses with different stats."},{e:"💨",t:"PUFF = SPEED",d:"Spam puff to make it run!"},{e:"⚡",t:"Manage stamina",d:"Puffs drain stamina. Rest to recover."},{e:"🏆",t:"Cross finish line",d:"First horse to 100% wins!"}], reward:50 },
  // Stage
  vibecheck:      { roles:[{id:"contestant",emoji:"🎯",name:"Contestant",sub:"Answer trivia"},{id:"audience",emoji:"👥",name:"Audience",sub:"Watch & react"}], puffGame:false, stats:[{v:"1.2K",l:"watching"},{v:"100",l:"enter"},{v:"1",l:"survives"}], hotStats:["100 entered, 1 survived — BRUTAL 🧠💀"], htp:[{e:"🧠",t:"Trivia question",d:"Host asks, you answer."},{e:"💨",t:"Puff your answer",d:"TAP=A, SHORT=B, MED=C, LONG=D."},{e:"❌",t:"Wrong = eliminated",d:"One wrong answer and you're OUT."},{e:"🏆",t:"Last standing",d:"Survive all rounds to win!"}], reward:80 },
  higherlower:    { roles:[{id:"contestant",emoji:"🎯",name:"Contestant",sub:"Guess stats"},{id:"audience",emoji:"👥",name:"Audience",sub:"Watch & react"}], puffGame:false, stats:[{v:"450",l:"guessing"},{v:"10",l:"rounds"},{v:"7",l:"best streak"}], hotStats:["7-round streak — galaxy brain 🧠✨"], htp:[{e:"📊",t:"See a stat",d:"A number is shown (e.g., '4.5M Google searches')."},{e:"🔼",t:"Higher or Lower?",d:"Is the NEXT stat higher or lower?"},{e:"💨",t:"Puff to guess",d:"Short=Lower, Long=Higher."},{e:"🔥",t:"Build streaks",d:"Consecutive correct = multiplier!"}], reward:60 },
  pricepuff:      { roles:[{id:"contestant",emoji:"🎯",name:"Contestant",sub:"Guess prices"},{id:"audience",emoji:"👥",name:"Audience",sub:"Watch & react"}], puffGame:false, stats:[{v:"200",l:"guessing"},{v:"$5→$50K",l:"range"},{v:"6",l:"rounds"}], hotStats:["Someone guessed $5 for a $50K car 😂💀"], htp:[{e:"🏷️",t:"See product",d:"A product is shown to you."},{e:"💨",t:"Puff = price",d:"Puff duration maps to your price guess."},{e:"🎯",t:"Closest wins",d:"Without going OVER the real price!"},{e:"🏆",t:"6 rounds",d:"Best total accuracy wins."}], reward:60 },
  survivaltrivia: { roles:[{id:"contestant",emoji:"🎯",name:"Contestant",sub:"Answer or die"},{id:"audience",emoji:"👥",name:"Audience",sub:"Watch & react"}], puffGame:false, stats:[{v:"800",l:"entering"},{v:"100",l:"start"},{v:"12s",l:"per question"}], hotStats:["40 eliminated on ONE question 💀","Phone-a-friend gave the WRONG answer 😂"], htp:[{e:"🧠",t:"Answer fast",d:"12 seconds per question."},{e:"❌",t:"Wrong = DEAD",d:"One mistake = instant elimination."},{e:"💨",t:"Puff answer",d:"TAP=A, SHORT=B, MED=C, LONG=D."},{e:"🏆",t:"100 enter, 1 wins",d:"Last brain standing!"}], reward:80 },
  simonpuffs:     { roles:[{id:"contestant",emoji:"🎯",name:"Contestant",sub:"Remember patterns"},{id:"audience",emoji:"👥",name:"Audience",sub:"Watch & react"}], puffGame:false, stats:[{v:"150",l:"memorizing"},{v:"8",l:"max rounds"},{v:"4",l:"colors"}], hotStats:["Someone remembered a 12-step pattern — MEMORY GOD 🧠"], htp:[{e:"🔴",t:"Watch the pattern",d:"Colors flash in sequence."},{e:"💨",t:"Repeat with puffs",d:"SHORT/MED/LONG/BLINKER = different colors."},{e:"❌",t:"Wrong = out",d:"Miss one step = eliminated."},{e:"🏆",t:"Longest memory",d:"Survive the most rounds!"}], reward:60 },
  puffauction:    { roles:null, puffGame:true, stats:[{v:"180",l:"bidding"},{v:"16",l:"bidders"},{v:"8.2s",l:"longest bid"}], hotStats:["World's Largest Joint sold for a 8.2s puff 💀🫁"], htp:[{e:"🔨",t:"Item for auction",d:"Absurd items up for grabs!"},{e:"💨",t:"PUFF = BID",d:"Hold puff to bid. Longest wins!"},{e:"🫁",t:"Lung management",d:"Your lung meter depletes each round."},{e:"🏆",t:"Win the item",d:"Highest bidder takes the prize!"}], reward:60 },
  // Oracle/Fortune
  crystalball:    { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"table",emoji:"🪑",name:"Table"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"450",l:"predicting"},{v:"54%",l:"accuracy"},{v:"11",l:"best streak"}], hotStats:["The oracle was wrong 7 times today. Fire the oracle. 🔮😂"], htp:[{e:"🔮",t:"See prediction",d:"A yes/no question appears."},{e:"💨",t:"Puff your answer",d:"Short=NO, Long=YES, Blinker=CERTAIN."},{e:"⚡",t:"Blinker risk",d:"CERTAIN: 3x if right, -2x if wrong!"},{e:"🏆",t:"5 rounds",d:"Build accuracy streak!"}], reward:50 },
  strainbattle:   { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"table",emoji:"🪑",name:"Table"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"380",l:"voting"},{v:"64",l:"strains"},{v:"50+",l:"voters"}], hotStats:["OG Kush beat Gorilla Glue — the chat RIOTED 🌿😂"], htp:[{e:"🌿",t:"Two strains",d:"Two strains face off."},{e:"💨",t:"Puff to vote",d:"Short=Left, Long=Right."},{e:"📊",t:"Results shown",d:"See how the community voted."},{e:"🏆",t:"5 matchups",d:"Vote with the majority for bonus!"}], reward:50 },
  matchpredictor: { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"table",emoji:"🪑",name:"Table"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"290",l:"predicting"},{v:"⚽",l:"WC matches"},{v:"6",l:"pundits"}], hotStats:["Someone predicted 5/5 correct — are they from the future? 🔮"], htp:[{e:"⚽",t:"See the match",d:"Two teams shown with stats."},{e:"💨",t:"Predict result",d:"Short=Home, Med=Draw, Long=Away."},{e:"📊",t:"Watch it unfold",d:"See if your prediction was right!"},{e:"🏆",t:"5 matches",d:"Most accurate pundit wins."}], reward:50 },
  dailypicks:     { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"group",emoji:"📊",name:"Daily Board"}], stats:[{v:"1.2K",l:"picked today"},{v:"54%",l:"avg right"},{v:"30",l:"max streak"}], hotStats:["Someone hit 30-day streak — LEGENDARY 🔥👑"], htp:[{e:"📅",t:"3 daily picks",d:"Morning, afternoon, night predictions."},{e:"💨",t:"Puff your pick",d:"Short or Long = different answers."},{e:"🔥",t:"Build streak",d:"Consecutive correct = multiplier!"},{e:"🏆",t:"30-day = legend",d:"Daily ritual — come back tomorrow!"}], reward:50 },
  puffslots:      { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"table",emoji:"🪑",name:"Table"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"380",l:"spinning"},{v:"3",l:"jackpots today"},{v:"1K",l:"biggest win"}], hotStats:["🌿🌿🌿 Someone hit the WEED JACKPOT 🎰💀"], htp:[{e:"🎰",t:"3 reels",d:"Match symbols to win!"},{e:"💨",t:"Puff to spin",d:"Hold and release to stop reels."},{e:"⚡",t:"Blinker bonus",d:"4.5s+ = guaranteed 2 match!"},{e:"💎",t:"Jackpot",d:"🌿=1000 · 7️⃣=500 · 💎=200"}], reward:50 },
  coinflip:       { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"group",emoji:"📊",name:"Group"}], stats:[{v:"600",l:"flipping"},{v:"50%",l:"it's fair!"},{v:"8",l:"flips/game"}], hotStats:["Heads came up 7 times in a row — rigged? 🪙😂"], htp:[{e:"🪙",t:"Pick a side",d:"Heads or Tails — 50/50 chance."},{e:"💨",t:"Puff confidence",d:"Longer puff = higher multiplier."},{e:"⚡",t:"Blinker = 5x",d:"Win 5x or lose 2x — BOLD!"},{e:"🏆",t:"8 flips",d:"Build your streak!"}], reward:50 },
  puffblackjack:  { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"table",emoji:"🪑",name:"Table"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"290",l:"at table"},{v:"48%",l:"house edge"},{v:"21",l:"blackjack!"}], hotStats:["Someone hit on 20. We don't talk about it. 🃏💀"], htp:[{e:"🃏",t:"Get dealt cards",d:"Try to reach 21 without going over."},{e:"💨",t:"Puff: Hit/Stand",d:"Short=HIT, Long=STAND."},{e:"⚡",t:"Blinker double",d:"4.5s+ = DOUBLE DOWN!"},{e:"🏆",t:"7 hands",d:"Beat the dealer for coins."}], reward:60 },
  crapsnclouds:   { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"table",emoji:"🪑",name:"Table"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"200",l:"rolling"},{v:"7",l:"lucky number"},{v:"8",l:"at table"}], hotStats:["Natural 7 on the come-out — TABLE ERUPTS 🎲🔥"], htp:[{e:"🎲",t:"Roll dice",d:"Puff duration influences the roll."},{e:"🎯",t:"7 or 11",d:"Come-out roll: 7/11 = instant win!"},{e:"💨",t:"Hot dice",d:"Blinker = +50% payout!"},{e:"🏆",t:"Hit your point",d:"Set a point, then hit it again."}], reward:50 },
  mysterybox:     { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"table",emoji:"🪑",name:"Table"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"350",l:"opening"},{v:"🎁",l:"3 boxes"},{v:"💎",l:"legendary!"}], hotStats:["Someone found a legendary on their FIRST pick 🎁✨"], htp:[{e:"🎁",t:"3 mystery boxes",d:"Pick one to open."},{e:"💨",t:"Puff to reveal",d:"Hold to open your box."},{e:"⚡",t:"Blinker upgrade",d:"Common → Rare guaranteed!"},{e:"💎",t:"Find legendary",d:"5 rounds of mystery!"}], reward:50 },
  scratchpuff:    { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"280",l:"scratching"},{v:"6",l:"zones"},{v:"3",l:"match to win"}], hotStats:["Matched 3 diamonds on a blinker scratch 💎💎💎"], htp:[{e:"🎫",t:"6 scratch zones",d:"Tap a zone to select it."},{e:"💨",t:"Puff to scratch",d:"Hold to reveal what's underneath."},{e:"🎯",t:"Match 3",d:"Find 3 matching symbols to win!"},{e:"⚡",t:"Blinker scratch",d:"Double prize on matches!"}], reward:50 },
  fortunecookie:  { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"table",emoji:"🪑",name:"Table"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"320",l:"cracking"},{v:"🥠",l:"wisdom"},{v:"8",l:"traders"}], hotStats:["The golden fortune was traded 3 times before reveal 😂"], htp:[{e:"🥠",t:"Cookie appears",d:"What fortune awaits?"},{e:"💨",t:"Puff to crack",d:"Hold to build suspense!"},{e:"📜",t:"Read fortune",d:"Wisdom + coins inside."},{e:"⚡",t:"Blinker = golden",d:"Premium fortune + bonus coins!"}], reward:50 },
  treasuremap:    { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"table",emoji:"🪑",name:"Table"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"250",l:"exploring"},{v:"16",l:"tiles"},{v:"3",l:"treasures"}], hotStats:["Hit a bomb RIGHT next to treasure — tragic 💣😢"], htp:[{e:"🗺️",t:"16 tiles",d:"3 treasures hidden, 3 bombs!"},{e:"👆",t:"Tap to select",d:"Choose which tile to dig."},{e:"💨",t:"Puff to dig",d:"Reveal what's underneath."},{e:"💎",t:"Find 3 treasures",d:"Avoid bombs — game over!"}], reward:50 },
  spinwin:        { modes:null, puffGame:false, fortunePlay:[{id:"solo",emoji:"🎲",name:"Solo"},{id:"table",emoji:"🪑",name:"Table"},{id:"group",emoji:"📊",name:"Group"},{id:"stream",emoji:"👀",name:"Stream It"}], stats:[{v:"400",l:"spinning"},{v:"12",l:"segments"},{v:"500",l:"gold wedge"}], hotStats:["GOLD WEDGE! 500 coins in one spin 🎡✨"], htp:[{e:"🎡",t:"Big wheel",d:"12 prize segments."},{e:"💨",t:"Puff to spin",d:"Puff force = spin power."},{e:"🎯",t:"Land on prize",d:"Each segment has different coins."},{e:"⚡",t:"Gold wedge",d:"Land on gold = 500+ coins!"}], reward:50 },
};

// ── WC PREDICTION DATA ──
export const ORACLE_WC_MATCHES = [
  {id:1, home:"USA", homeFlag:"🇺🇸", away:"Mexico", awayFlag:"🇲🇽", time:"Tonight 9PM", group:"A", hot:true, predictions:{home:45,draw:28,away:27}},
  {id:2, home:"Brazil", homeFlag:"🇧🇷", away:"Germany", awayFlag:"🇩🇪", time:"Tomorrow 3AM", group:"B", predictions:{home:52,draw:22,away:26}},
  {id:3, home:"France", homeFlag:"🇫🇷", away:"Argentina", awayFlag:"🇦🇷", time:"Tomorrow 9PM", group:"C", hot:true, predictions:{home:38,draw:25,away:37}},
  {id:4, home:"England", homeFlag:"🏴󠁧󠁢󠁥󠁮󠁧󠁿", away:"Spain", awayFlag:"🇪🇸", time:"Wed 6PM", group:"D", predictions:{home:35,draw:30,away:35}},
  {id:5, home:"Japan", homeFlag:"🇯🇵", away:"Netherlands", awayFlag:"🇳🇱", time:"Wed 9PM", group:"E", predictions:{home:28,draw:25,away:47}},
  {id:6, home:"Vietnam", homeFlag:"🇻🇳", away:"Portugal", awayFlag:"🇵🇹", time:"Thu 3AM", group:"F", predictions:{home:15,draw:20,away:65}},
];

export const ORACLE_WC_SPECIALS = [
  {id:"winner", question:"Who wins the World Cup?", emoji:"🏆", topPick:"Brazil 🇧🇷", topPct:24, total:3847},
  {id:"scorer", question:"Top Scorer?", emoji:"⚽", topPick:"Mbappé 🇫🇷", topPct:18, total:2103},
  {id:"dark", question:"Dark Horse Team?", emoji:"🐴", topPick:"Japan 🇯🇵", topPct:15, total:1456},
  {id:"group_death", question:"Group of Death?", emoji:"💀", topPick:"Group C", topPct:42, total:890},
];

// ── GAME DATA LOOKUPS ──
export const KICK_ZONES = [
  { label:"↖", col:0, row:0 }, { label:"⬆", col:1, row:0 }, { label:"↗", col:2, row:0 },
  { label:"↙", col:0, row:1 }, { label:"⬇", col:1, row:1 }, { label:"↘", col:2, row:1 },
];

export const CHAT_BOTS = ["VibeKing","ChillMaster","NeonQueen","BlazedPanda","CloudNine99","PuffDaddy","MoodMaster"];
export const CHAT_MSGS = ["Let's go! 🔥","Ez 😎","GG 👏","Nah that's cap 💀","LETSGOOO 🎉","🤯🤯🤯","Hmm tricky 🤔","W play 🏆","Clutch! 💪","Prediction locked 🔮"];
